version: '3.7'

services:
  placeholder-etl:
    build: .
    container_name: placeholder-etl
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ENV=production
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=placeholder_db
    ports:
      - "8080:8080"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: placeholder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d placeholder_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
